[project]
name = "open-source-ai-docs"
version = "1.0.0"
description = "A detailed setup documentation for using the open source AI models"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "zensical>=0.0.37",
]

[tool.setuptools.find]
exclude = ["site*", "overrides*"]